### PR TITLE
Link org to session

### PR DESCRIPTION
**Pull request by cecemel**

### CODE REVIEW

**Comment by benjay10** [comment]
This feels redundant because a Session is linked to an Account that *always* has an organisation linked to it. This is checked when logging in during the `verifyPublisherKeyOrganisation` function. If anything does not exist, the client can not log in (we should check if that is really the case though, that code is copied from the automatic-submission-service).
Since you did not give any motivation here on the PR, is there anything else you are trying to achieve/protect against?

**Comment by cecemel** [comment]
> This feels redundant because a Session is linked to an Account that _always_ has an organisation linked to it. This is checked when logging in during the `verifyPublisherKeyOrganisation` function. If anything does not exist, the client can not log in (we should check if that is really the case though, that code is copied from the automatic-submission-service). Since you did not give any motivation here on the PR, is there anything else you are trying to achieve/protect against?

A more fine grained approach is better; if things change, the session can be deleted for that particular instance. Furthermore, once we allow writing stuff to graphs, mu-auth makes sure only the specific graph gets updated

**Comment by benjay10** [comment]
But this is not more fine grained. A session has exactly one account and an account has exactly one organisation. Adding the organisation to the session is just duplicated information and one more triple to lose track of. If some vendor needs to manage multiple organisations, we should just make more accounts, right?

**Comment by cecemel** [comment]
> But this is not more fine grained. A session has exactly one account and an account has exactly one organisation. Adding the organisation to the session is just duplicated information and one more triple to lose track of. If some vendor needs to manage multiple organisations, we should just make more accounts, right?

Yes it is clumsy. Yes vendors have multiple entities they support for the same Agent, not account. Yes we have a migration path towards a better multi account support (see thread in parallel chat) No it won't result in less triples. 

For reading: if we don't link the org,  a vendor will have access for ALL organizations for one deploy  instance of their app (e.g some are even physically deployed per org). This might lead to cluster fucks if whatever confidential data is added to this graph. 
For writing: if not linked to the org, graphs might get contaminated due to how mu-auth works.

This is the best we currently have. A migration path is there and if we already link it now with org, the migration will be completely transparent for the vendor. So let's just start with this.

**Review by benjay10 — APPROVED** [review]
Okay, then I can see no other fault in including these changes.

**Pull request merged**
